POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "title": "Video node",
    "description": "Video 01 description",
    "duration": 60
}

###
# GET http://localhost:8080/health
GET http://localhost:8080/usuarios 
# GET http://localhost:8080/usuarios?search=node

###
PUT http://localhost:8080/usuarios/3931e22e-ebcb-45c4-a8e9-2cc52d00bfd7
Content-Type: application/json

{
    "title": "Video Nodeeee",
    "description": "Video 01 description",
    "duration": 60
}

###
DELETE http://localhost:8080/usuarios/37ba28bd-8d72-4055-9929-f28c7a3f594d