POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nome": "Camila",
    "data_nascimento": "1991-01-01",
    "idade": 34,
    "sexo": "Feminino",
    "email": "cami@gmail.com",
    "senha": "123456"
}

###
# GET http://localhost:8080/health
GET http://localhost:8080/usuarios 
# GET http://localhost:8080/usuarios?search=cami

###
PUT http://localhost:8080/usuarios/2
Content-Type: application/json

{
    "id": 2,
    "nome": "Camila",
    "idade": 28,
    "email": "bruno@gmail.com",
    "data_nascimento": "1997-02-28",
    "sexo": "Masculino",
    "senha": "123456"
}

###
DELETE http://localhost:8080/usuarios/7